language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
addons:
  firefox: latest
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar -xvf geckodriver-v0.21.0-linux64.tar.gz
script:
  - py.test tests.py